//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KRnovyjj
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотpудники.
    /// </summary>
    // *** Start programmer edit section *** (Сотpудники CustomAttributes)

    // *** End programmer edit section *** (Сотpудники CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Сотpудники : ICSSoft.STORMNET.DataObject
    {
        
        private int fТабель;
        
        private string fФИО;
        
        private string fДолжность;
        
        // *** Start programmer edit section *** (Сотpудники CustomMembers)

        // *** End programmer edit section *** (Сотpудники CustomMembers)

        
        /// <summary>
        /// Должность.
        /// </summary>
        // *** Start programmer edit section *** (Сотpудники.Должность CustomAttributes)

        // *** End programmer edit section *** (Сотpудники.Должность CustomAttributes)
        [StrLen(255)]
        public virtual string Должность
        {
            get
            {
                // *** Start programmer edit section *** (Сотpудники.Должность Get start)

                // *** End programmer edit section *** (Сотpудники.Должность Get start)
                string result = this.fДолжность;
                // *** Start programmer edit section *** (Сотpудники.Должность Get end)

                // *** End programmer edit section *** (Сотpудники.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотpудники.Должность Set start)

                // *** End programmer edit section *** (Сотpудники.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (Сотpудники.Должность Set end)

                // *** End programmer edit section *** (Сотpудники.Должность Set end)
            }
        }
        
        /// <summary>
        /// Табель.
        /// </summary>
        // *** Start programmer edit section *** (Сотpудники.Табель CustomAttributes)

        // *** End programmer edit section *** (Сотpудники.Табель CustomAttributes)
        public virtual int Табель
        {
            get
            {
                // *** Start programmer edit section *** (Сотpудники.Табель Get start)

                // *** End programmer edit section *** (Сотpудники.Табель Get start)
                int result = this.fТабель;
                // *** Start programmer edit section *** (Сотpудники.Табель Get end)

                // *** End programmer edit section *** (Сотpудники.Табель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотpудники.Табель Set start)

                // *** End programmer edit section *** (Сотpудники.Табель Set start)
                this.fТабель = value;
                // *** Start programmer edit section *** (Сотpудники.Табель Set end)

                // *** End programmer edit section *** (Сотpудники.Табель Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Сотpудники.ФИО CustomAttributes)

        // *** End programmer edit section *** (Сотpудники.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Сотpудники.ФИО Get start)

                // *** End programmer edit section *** (Сотpудники.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Сотpудники.ФИО Get end)

                // *** End programmer edit section *** (Сотpудники.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотpудники.ФИО Set start)

                // *** End programmer edit section *** (Сотpудники.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Сотpудники.ФИО Set end)

                // *** End programmer edit section *** (Сотpудники.ФИО Set end)
            }
        }
    }
}
